require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - '**/*.jbuilder'
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - config/environments/*.rb
    - config/*.rb
    - config.ru

Style/FrozenStringLiteralComment:
  Exclude:
    - config/environments/*.rb
    - config/initializers/*.rb
    - config/*.rb
    - config.ru

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false